### ISSUE TITLE
Добавить подстановку значений переменных в сохраняемый в переменную текст

### ISSUE THREAD

**Issue by zenden231** [alfa-laboratory/Molder#136]
В паттерн **я сохраняю текст в переменную "(.+)":** добавить метод ReplaceVariables контроллера переменных, который по наличию якорей в сохраняемом тексте будет:
- находить переменные контекста и подставлять их значения
- в случае отсутствия в контексте переменных, на которые ссылается якорь, оставлять строку = название якоря

**Comment by zenden231** [comment]
+ модифицировать работу с json объектами: 
- якорь с названием переменной - без кавычек
- в случае отсутствия значения переменной - заменять на строковое название якоря + кавычки
- в случае null значения переменной - подставлять null без кавычек
- в случае наличия не null значения переменной - подставлять значение переменной в двойных кавычках

**Comment by egorsh0** [comment]
Предложенная функциональность не будет работать в рамках следующих примеров:
1) переменная test имеет числовой или bool тип и подставляется в json
При наличии значения добавляются кавычки, что излишне (хоть и не нарушает схему) в json
2) подстановка любых значений в строку
Пример:
code is a {{test}}
test не существует - code is a test
test равна null - code is a null
test существует и равно 1 - code is a "1"
