### ISSUE TITLE
Изменить или добавить шаг проверки переменной на НЕ содержит

### ISSUE THREAD

**Issue by alexius595** [alfa-laboratory/Molder#211]
Сейчас если проверяем переменную с NULL на Не содержит, то возникает ошибка. Логично что если мы ожидаем отсутствия значение, то и NULL вполне адекватный результат. Предлагаю считать NULL значение удовлетворяющим условию "Не содержит".
Для дополнительной проверки есть шаги проверки на существование, а вот если это не принципиально и результат Nullable, но не всегда NULL, проверить не чем, т.к. if - else тут нет

**Comment by irisha777** [comment]
взял в работу
