### ISSUE TITLE
NullRef Exception при обработке timeout от web-сервиса

### ISSUE THREAD

**Issue by alexius595** [alfa-laboratory/Molder#218]
public static class FlurlExceptionsHelper
    {
        public static ResponceInfo GetResponce(this Exception ex, RequestInfo request)
        {
            if (ex is not FlurlException flurlException) return null;
            switch (flurlException.ExceptionName)
            {
                case nameof(FlurlHttpTimeoutException):
                    return new ResponceInfo
                    {
                        Headers = null,
                        Content = null,
                        StatusCode = System.Net.HttpStatusCode.GatewayTimeout,
                        Request = request
                    };
                case nameof(FlurlHttpException):
                {
                    var exception = (flurlException.Exception as FlurlHttpException)?.Call.Response;
                    var content = exception?.ResponseMessage.Content.ReadAsStringAsync().Result;

                    var responce = new ResponceInfo
                    {
                        Headers = null,
                        Content = content,
**//exception здесь оказался null при маленьком timeout
                        StatusCode = exception.ResponseMessage.StatusCode,**
                        Request = request
                    };

                    Log.Logger().LogInformation($"{responce.CreateMessage()}. \n\nInner exception: {ex}");
                    return responce;
                }
                default:
                    return null;
            }
        }
    }

**Comment by alexius595** [comment]
опечатка была в адресе, но все равно лучше как-то обработать

**Comment by egorsh0** [comment]
А что было в сгенерированном catch?

**Comment by alexius595** [comment]
ex2.Exception
{"Call failed. No such host is known. (urlservice:80): GET http://urlService/api/NettingDeals?br=10&customer=8803849&vdate=1/25/2022 12:00:00 AM"}
System.Exception {Flurl.Http.FlurlHttpException}

**Comment by alexius595** [comment]
не ту переменную взял просто
